# Use an official OpenJDK runtime as the base image (Apple Silicon ke liye ARM64 bhi specify karein)
FROM --platform=linux/arm64 openjdk:11

# Set the working directory
WORKDIR /app

# Copy the Spring Boot application JAR file into the container
COPY ./target/springboottest-0.0.1-SNAPSHOT.jar springboottest-0.0.1-SNAPSHOT.jar

# Expose port 8084
EXPOSE 8084

# Define the command to run your Spring Boot application
CMD ["java", "-jar", "springboottest-0.0.1-SNAPSHOT.jar"]